### ISSUE TITLE
what is the EPOCHS？

### ISSUE THREAD

**Issue by lishowmaker** [sari-saba-sadiya/EEGExtract#1]
I would like to know how EPOCHS is selected in your library code.And I don't understand it after reading your paper. Is it obtained by dividing the signal acquired by the whole channel into several segments?How is it divided?

**Comment by sari-saba-sadiya** [comment]
Hi,

In most applications an "Epoch" can be thought of as a trial. It is a common term in EEG research.

To be precise, an epoch is a segment of interest extracted from EEG data. We used EEGLAB to extract our Epochs, this was done by first "bining" segments from a continuous signal based on markers denoting the trial type (condition/label) and then extracting the epochs by looking at a specific time window. The python library "MNE" has a similar process with a few examples that might be useful: https://mne.tools/0.16/generated/mne.Epochs.html#mne.Epochs
