### ISSUE TITLE
what are the “bin_min”, “bin_max”, “binWidth"

### ISSUE THREAD

**Issue by lishowmaker** [sari-saba-sadiya/EEGExtract#2]
In the library, When shannonEntropy was evaluated，I want to know how “bin_min”， “bin_max”, and ”binWidth" were determined. That is to say, When I use this function, how do I pass in these parameters	

Thank you very very much！

**Comment by sari-saba-sadiya** [comment]
Hi,

The binning is just to convert the EEG data to discrete form for entropy calculation. One option that always works is to set the bin_min/max to be the highest / lowest values in the data array and the bin width to 1.

Regards

**Comment by deskool** [comment]
> In the library, When shannonEntropy was evaluated，I want to know how “bin_min”， “bin_max”, and ”binWidth" were determined. That is to say, When I use this function, how do I pass in these parameters
> 
> Thank you very very much！

Hi @lishowmaker ,

Thank for your interest in our work! Measures like entropy are sensitive to the `binWidth`. [This Stack Exchange post](https://stats.stackexchange.com/questions/197499/what-is-the-best-way-to-decide-bin-size-for-computing-entropy-or-mutual-informat) describes a way to choose the optimal number of bins (with code too!).

Let us know if you have any other questions.
