### ISSUE TITLE
How do I set k_max when I calculate the hFD

### ISSUE THREAD

**Issue by lishowmaker** [sari-saba-sadiya/EEGExtract#3]
I looked up some information, but I still couldn't solve the problem. It has been bothering me for a long time.
I know it's the maximum time interval between picking m.

**Comment by sari-saba-sadiya** [comment]
This is a complex question, the answer is "it depends".

As I am sure you know the Higuchi Fractal Dimension indicates [the mean of means (size of boxes and length of steps) of number of boxes that can contain a time series](https://en.wikipedia.org/wiki/Higuchi_dimension) (Its the slope at (log(1/k),log(1/k sum(L(m,k)) so you can do the derivation). 

Basically this tells you how "jittery" the signal is, the smoother the signal the lower the hFD (you can test this). This means that for different applications a different number of K is necessary. Personally for <500Hz EEG signals I have found that values around 27 do the trick.
